version: '3'
services:
  redis-server: 
    image: 'redis'
    ports:
      - "6379:6379" 
    restart: on-failure

  node-app:
    image: "alpine:node"
    build: .
    volumes: 
      - "./app:/usr/app"
    depends_on:
     - redis
    ports:
      - "3000:3000"
    restart: on-failure